draft_lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
from lab_1.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^$', index)
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, friend_list_json

urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^add-friend/$', add_friend, name='add-friend'),
    url(r'^validate-npm/$', validate_npm, name='validate-npm'),
    url(r'^delete-friend/$', delete_friend, name='delete-friend'),
    #url(r'^delete-friend/(?P<friend_id>[0-9]+)/$', delete_friend, name='delete-friend'),
    url(r'^get-friend-list/$', friend_list, name='get-friend-list'),
    url(r'^get-friend-list-json/$', friend_list_json, name = 'get-friend-list-json')

]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
from lab_2.views import index as index_lab2
from django.views.generic import RedirectView
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10.urls as lab_10

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/',include(lab_2_addon,namespace="lab-2-addon")),
    url(r'^$', RedirectView.as_view(permanent='True', url='/lab-4/')),
    url(r'^lab-3/', include(lab_3,namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10'))
]

lab_7/models.py
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

class Mahasiswa(models.Model):
	mahasiswa_name = models.CharField(max_length=400)
	npm = models.CharField(max_length=250)

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers

from .models import Friend, Mahasiswa
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()

    for mahasiswaEntry in mahasiswa_list:
        Mahasiswa.objects.get_or_create(mahasiswa_name=mahasiswaEntry['nama'],npm=mahasiswaEntry['npm'])

    friend_list = Friend.objects.all()
    mahasiswa_list = Mahasiswa.objects.all()

    paginator = Paginator(mahasiswa_list, 25)

    page = request.GET.get('page')
    try:
        collected = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        collected = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        collected = paginator.page(paginator.num_pages)

    response = {"mahasiswa_list": collected, "friend_list": friend_list}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def friend_list(request):
    friend_list = Friend.objects.all()
    response['friend_list'] = friend_list
    html = 'lab_7/daftar-teman.html'
    return render(request, html, response)

def friend_list_json(request):
    SomeModel_json = serializers.serialize("json", Friend.objects.all())
    data = {"SomeModel_json": SomeModel_json}
    return JsonResponse(data)

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        friend = Friend(friend_name=name, npm=npm)
        friend.save()
        data = model_to_dict(friend)
        return HttpResponse(data)

@csrf_exempt
def delete_friend(request):
    if request.method == 'POST':
        npm = request.POST.get('npm',None)
        print(npm)
        if npm != None:
            Friend.objects.filter(npm=npm).delete()
            data = {'ok': True}
            return JsonResponse(data)

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    entry = Friend.objects.filter(npm = npm)
    data = {
        'is_taken': len(entry) >= 1
    }
    return JsonResponse(data)

def model_to_dict(obj):
    data = serializers.serialize('json', [obj,])
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/daftar-teman.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
    <section name="friend-list" id="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block javascript %}
    <script>
        var deleteFriend = function(npm) {
            $.ajax({
            method: "POST",
            url: '{% url "lab-7:delete-friend" %}',
            data: {
                'npm': npm
            },
            success: function (data) {
                alert(npm+" dihapus dari data");
                $("."+npm).remove();
            }
            });
        };
        $( document ).ready(function () {
            $.ajax({
                method: "GET",
                url:'{% url "lab-7:get-friend-list-json" %}',
                success: function (response) {
                    hasil = JSON.parse(response['SomeModel_json']);
                    console.log(hasil.length);
                    for(var I=0; I<hasil.length ; I++){
                        var npm = hasil[I]["fields"]["npm"];
                        var nama = hasil[I]["fields"]["friend_name"];
                        html = '<a class="list-group-item clearfix '+npm+'">' +
                                nama + " (" + npm + ")" +
                                '<span class="pull-right"><span class="delete-button btn-xs btn-default" onclick=deleteFriend("'+npm+'")>'
                                + 'Delete dari daftar teman </span></span></a></a>'
                        console.log(html);
                        $("#friend-list").append(html);
                    }
                },
                error: function(error){
                    //tampilkan pesan error
                }
            });
        });
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.mahasiswa_name }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                            <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.mahasiswa_name }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
            <span class="step-links">
                {% if mahasiswa_list.has_previous %}
                    <a href="?page={{ contacts.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ mahasiswa_list.number }} of {{ mahasiswa_list.paginator.num_pages }}.
                </span>

                {% if mahasiswa_list.has_next %}
                    <a href="?page={{ mahasiswa_list.next_page_number }}">next</a>
                {% endif %}
            </span>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST",
            url: "{% url "lab-7:add-friend" %}",
            data: { name: nama, npm: npm},
            success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                    nama + " (" + npm + ")"
                    '</a>';
                $("#friend-list").append(html)
                $('.alert').remove()
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman");
            }
        });
    };
    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault();
    });
    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });
</script>
{% endblock %}